### PR TITLE
Ignore the global plugin when updating local projects

### LINKED ISSUE #38: Interferes with other projects when installed globally
I found this issue when installing a tool globally which depended on `ocramius/package-versions`.

It will then try to write package versions for any other composer project when an update is performed, it will subsequently fail because the folder structure it expects to exist, doesn't.

To reproduce:

```
composer global require ocramius/package-versions
cd ~
mkdir package-versions-test
cd package-versions-test
composer require monolog/monolog
```

The output will be something along the lines of:

```
Using version ^1.21 for monolog/monolog
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Prefetch start: total: 2
    Finished: success:0, skipped:2, failure:0, total: 2
  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing monolog/monolog (1.21.0)
    Loading from cache

monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Writing lock file
Generating autoload files
Changelogs summary:

 - psr/log installed in version 1.0.2
   Release notes: https://github.com/php-fig/log/releases/tag/1.0.2

 - monolog/monolog installed in version 1.21.0
   Release notes: https://github.com/Seldaek/monolog/releases/tag/1.21.0

ocramius/package-versions:  Generating version class...

Installation failed, deleting ./composer.json.


  [ErrorException]
  file_put_contents(/Users/aydin/package-versions-test/vendor/ocramius/package-versions/src/PackageVersions/Versions.php): failed to open stream: No such file or directory


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

Note that for my use-case I do not actually install the tool globally, but another tool which depends on `package-versions`. I just directly installed here to ease the test case.

I'm not sure what we could do about this, any ideas?

### PR DESCRIPTION
**Pull request by AydinHassan**
I had to refactor a little to reduce repeating code, anyway this fixes #38.

However, I've had a think and I don't know how we can provide an e2e test. We could provide some project assets but we'd have to mess with the systems global composer project, which I don't think we can do safely.

I've also had to modify existing tests, I wasn't sure how to get them working now that we need `ocramius/package-versions` to be present in the locker.

Thoughts @Ocramius ?

### CODE REVIEW

**Comment by AydinHassan** [comment]
This patch also has the added benefit of fixing another crash. After removing `ocramius/package-versions` the plugin still runs an attempts to generate the version file, but the folder does not exist anymore.

Running: `composer remove ocramius/package-versions` (before this patch) results in:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing ocramius/package-versions (1.1.1)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...

Removal failed, reverting ./composer.json to its original content.

                                                                                                                                                                                 
  [ErrorException]                                                                                                                                                               
  file_put_contents(/Users/aydin/projects/package-versions-test/vendor/ocramius/package-versions/src/PackageVersions/Versions.php): failed to open stream: No such file or directory  
                                                                                                                                                                                 

remove [--dev] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--no-update-with-dependencies] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

**Comment by AydinHassan** [comment]
@Ocramius managed to get an E2E test working - it's a bit gross so I'd appreciate any pointers for it 😄

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+
+        $files = array_filter(
+            iterator_to_array(new RecursiveIteratorIterator(
+                new RecursiveCallbackFilterIterator(
+                    new RecursiveDirectoryIterator(realpath(__DIR__ . '/../../'), RecursiveDirectoryIterator::SKIP_DOTS),
+                    function (SplFileInfo $file) {
+                        $filePath = substr($file->getRealPath(), strlen(realpath(__DIR__ . '/../../')) + 1);
+
+                        if (substr($filePath, 0, 4) === '.git'
+                            || substr($filePath, 0, 5) === '.idea'
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Simply skip anything that starts with `.`

Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: There's something in the recursive directory iterator for that, btw

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+        $zip->open($this->tempArtifact . '/ocramius-package-versions-1.0.0.zip', ZipArchive::CREATE);
+
+        $files = array_filter(
+            iterator_to_array(new RecursiveIteratorIterator(
+                new RecursiveCallbackFilterIterator(
+                    new RecursiveDirectoryIterator(realpath(__DIR__ . '/../../'), RecursiveDirectoryIterator::SKIP_DOTS),
+                    function (SplFileInfo $file) {
+                        $filePath = substr($file->getRealPath(), strlen(realpath(__DIR__ . '/../../')) + 1);
+
+                        if (substr($filePath, 0, 4) === '.git'
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: This block is a negated boolean expression, not an if/else block

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 3]
```diff
@@ -0,0 +1,222 @@
+<?php
+
+namespace PackageVersionsTest;
+
+use PHPUnit_Framework_TestCase;
+use RecursiveCallbackFilterIterator;
+use RecursiveDirectoryIterator;
+use RecursiveIteratorIterator;
+use SplFileInfo;
+use ZipArchive;
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: This class is not part of the dev requirements

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 4]
```diff
@@ -0,0 +1,222 @@
...
+
+    private function createArtifact()
+    {
+        $zip = new ZipArchive();
+
+        $zip->open($this->tempArtifact . '/test-package-2.0.0.zip', ZipArchive::CREATE);
+        $zip->addFromString('composer.json', json_encode([
+             'name'    => 'test/package',
+             'version' => '2.0.0',
+         ], JSON_PRETTY_PRINT)).
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Alignment broken here too

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 5]
```diff
@@ -0,0 +1,222 @@
...
+            $this->tempLocalComposerHome . '/vendor/ocramius/package-versions/src/PackageVersions/Versions.php'
+        );
+
+        $this->execInDir('composer remove ocramius/package-versions -vvv', $this->tempLocalComposerHome);
+        $this->assertFileNotExists(
+            $this->tempLocalComposerHome . '/vendor/ocramius/package-versions/src/PackageVersions/Versions.php'
+        );
+    }
+
+    private function createPackageVersionsArtifact()
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Should this return the path to the generated artifact?

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 6]
```diff
@@ -0,0 +1,222 @@
...
+        $currentDir = getcwd();
+        chdir($dir);
+        $output = $this->exec($command);
+        chdir($currentDir);
+        return $output;
+    }
+
+    private function exec(string $command) : array
+    {
+        exec($command . ' 2> /dev/null', $output);
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: You need to assert that the exit code is `0`

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 3 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Added

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 7]
```diff
@@ -0,0 +1,222 @@
...
+use RecursiveCallbackFilterIterator;
+use RecursiveDirectoryIterator;
+use RecursiveIteratorIterator;
+use SplFileInfo;
+use ZipArchive;
+
+/**
+ * @author Aydin Hassan <aydin@hotmail.co.uk>
+ */
+class E2EInstaller extends PHPUnit_Framework_TestCase
```
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Sure thing - wasn't really sure how to name it

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 8]
```diff
@@ -0,0 +1,222 @@
...
+{
+    private $tempGlobalComposerHome;
```
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: added

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 9]
```diff
@@ -0,0 +1,222 @@
...
+        $this->rmDir($this->tempGlobalComposerHome);
+        $this->rmDir($this->tempLocalComposerHome);
+        $this->rmDir($this->tempArtifact);
+    }
+
+    public function testGloballyInstalledPluginDoesNotGenerateVersionsForLocalProject()
+    {
+        $this->createPackageVersionsArtifact();
+
+        file_put_contents($this->tempGlobalComposerHome . '/composer.json', json_encode([
```
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: fixed up - I introduced a method to write

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 10]
```diff
@@ -0,0 +1,222 @@
...
+                   'packagist' => false,
+               ],
+               [
+                   'type' => 'artifact',
+                   'url' => $this->tempArtifact,
+               ]
+           ]
+       ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
+
+        $this->execInDir('composer update -vvv', $this->tempLocalComposerHome);
```
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: fixed

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 5 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: I dont think so - the path to the zip isn't used for anything, just the folder where they reside

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 2 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: I've simplified this a little

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 1 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: You got a link? I couldn't find anything other than `SKIP_DOTS` which doesn't consider anything other than `..` & `.`

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 4 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: fixed

File: test/PackageVersionsTest/E2EInstallerTest.php (hunk 6 above)
Comment (AydinHassan) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Added an assertion in

**Comment by AydinHassan** [comment]
Seems to be failing on lowest deps - trying to figure out now

**Comment by AydinHassan** [comment]
Hmm - the composer exec output seems to print errors such as

```
Fatal error: Uncaught Error: Class 'Symfony\Component\Process\ProcessUtils' not found in /Users/aydin/projects/PackageVersions/vendor/composer/composer/src/Composer/Util/ProcessExecutor.php on line 124
```

**Comment by Ocramius** [comment]
> On further investigation I would say this is a bug with Composer:

We should then report it in composer and bump the required version there, I suppose...

**Comment by AydinHassan** [comment]
I've filed https://github.com/composer/composer/issues/5828 & created https://github.com/composer/composer/pull/5831 to fix it (maybe). I've bumped the minimum in here to `^2.3` also - should get the tests running.

File: composer.json [hunk 11]
```diff
@@ -16,7 +16,8 @@
     "require-dev": {
         "phpunit/phpunit":   "^5.4.7",
         "composer/composer": "^1.2.0",
-        "ext-zip": "*"
+        "ext-zip":           "*",
+        "symfony/process":   "^2.3"
```
Comment (Ocramius) [inline composer.json]: Note: this required should be pushed into composer

**Comment by AydinHassan** [comment]
OK composer/composer#5831 is merged now - guessing you want to wait for a tag before we pursue this?

**Comment by AydinHassan** [comment]
hey @Ocramius composer 1.3 has been released with the necessary fixes. Tests are passing now 😄 .

**Comment by Ocramius** [comment]
@AydinHassan looking good! Going through a quick sweep of the code, then merging :-)

File: src/PackageVersions/Installer.php [hunk 12]
```diff
@@ -80,27 +80,33 @@ public static function getSubscribedEvents()
      */
     public static function dumpVersionsClass(Event $composerEvent)
     {
-        $io = $composerEvent->getIO();
+        $composer = $composerEvent->getComposer();
+        $versions = iterator_to_array(self::getVersions($composer->getLocker(), $composer->getPackage()));
 
-        $io->write('<info>ocramius/package-versions:</info>  Generating version class...');
+        if (!isset($versions['ocramius/package-versions'])) {
+            //plugin must be globally installed - we only want to generate versions for projects which specifically
```
Comment (Ocramius) [inline src/PackageVersions/Installer.php]: @AydinHassan just a doubt, given that there's no real way to know from the code: what about when the package is indirectly depending on `package-versions`? Will it still run?

File: src/PackageVersions/Installer.php [hunk 13]
```diff
@@ -80,27 +80,33 @@ public static function getSubscribedEvents()
      */
     public static function dumpVersionsClass(Event $composerEvent)
     {
-        $io = $composerEvent->getIO();
+        $composer = $composerEvent->getComposer();
+        $versions = iterator_to_array(self::getVersions($composer->getLocker(), $composer->getPackage()));
 
-        $io->write('<info>ocramius/package-versions:</info>  Generating version class...');
+        if (!isset($versions['ocramius/package-versions'])) {
```
Comment (Ocramius) [inline src/PackageVersions/Installer.php]: Should probably be an `array_key_exists()` at this point - don't trust the value below it

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 14]
```diff
@@ -0,0 +1,243 @@
...
+    public function setUp()
+    {
+        $this->tempGlobalComposerHome = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/global';
+        $this->tempLocalComposerHome = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/local';
+        $this->tempArtifact = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/artifacts';
+        mkdir($this->tempGlobalComposerHome, 0777, true);
+        mkdir($this->tempLocalComposerHome, 0777, true);
+        mkdir($this->tempArtifact, 0777, true);
+
+        putenv('COMPOSER_HOME=' . $this->tempGlobalComposerHome);
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: This environment variable must be reset in `tearDown`

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 15]
```diff
@@ -0,0 +1,243 @@
...
+     * @var string
+     */
+    private $tempArtifact;
+
+    public function setUp()
+    {
+        $this->tempGlobalComposerHome = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/global';
+        $this->tempLocalComposerHome = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/local';
+        $this->tempArtifact = sys_get_temp_dir() . '/' . uniqid('InstallerTest', true) . '/artifacts';
+        mkdir($this->tempGlobalComposerHome, 0777, true);
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Please use `0700` for test runs

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 16]
```diff
@@ -0,0 +1,243 @@
...
+        mkdir($this->tempLocalComposerHome, 0777, true);
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Please use `0700` for test runs

File: test/PackageVersionsTest/E2EInstallerTest.php [hunk 17]
```diff
@@ -0,0 +1,243 @@
...
+        mkdir($this->tempArtifact, 0777, true);
```
Comment (Ocramius) [inline test/PackageVersionsTest/E2EInstallerTest.php]: Please use `0700` for test runs

File: src/PackageVersions/Installer.php (hunk 12 above)
Comment (Ocramius) [inline src/PackageVersions/Installer.php]: Also: what about when we are currently operating *in* package-versions?

Comment (AydinHassan) [inline src/PackageVersions/Installer.php]: @Ocramius will run in both contexts as it would be in the lock file - is that expected?

The first is actually my use case - A globally installed tool depends on `PackageVersions`.

Comment (Ocramius) [inline src/PackageVersions/Installer.php]: @AydinHassan great, thanks!

**Comment by Ocramius** [comment]
LGTM! \o/

**Comment by weirdan** [comment]
@samsonasik are there chances this will get backported to your fork? There's no way to report issues on forks, unfortunately.

**Comment by samsonasik** [comment]
@weirdan I tried backport but it seems needs very long time to get it work as I state at https://github.com/samsonasik/PackageVersions/pull/3#issuecomment-335073563 . Pull Request open if you can invest a time to patch ;)

**Comment by Ocramius** [comment]
I know @samsonasik did the backport with good intentions, but if you want to talk about older PHP versions support here, I'm gonna lock the thread: just upgrade your installation to a contemporary PHP binary.

**Comment by weirdan** [comment]
Oh, we were merely talking about porting changes from upstream to the fork. And I'm running 7.1, which, last time I checked, was pretty contemporary.

**Comment by Ocramius** [comment]
Then you don't need the fork ;-)
